### ISSUE TITLE
When are the todos in bigquery going to be implemented? Columns missing

### ISSUE THREAD

**Issue by mariana-s-fernandes** [fishtown-analytics/snowplow#113]
### Describe the bug
The final output tables for BigQuery are missing useragent and pref_timing columns. See the view for `snowplow_page_views.sql`

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: dbt-labs/dbt_utils
    version: ["1.0.0"]
  - package: calogica/dbt_expectations
    version: [">=0.5.0", "<0.9.0"]
  - package: dbt-labs/snowplow
     version: ["0.15.0"]
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.3.2
  - latest:    1.4.0 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.3.0 - Up to date!
```

**The operating system you're using:**

**The output of `python --version`:**
